# Generated by Django 4.0.4 on 2022-04-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='date_mail',
            field=models.DateTimeField(blank=True, max_length=30),
        ),
    ]
