# Generated by Django 4.0.4 on 2022-04-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0002_alter_communication_date_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='date_mail',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='communication',
            name='receiver',
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='date_mail',
            field=models.DateTimeField(),
        ),
    ]
