# Generated by Django 4.0.4 on 2022-04-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0003_alter_communication_date_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='communication_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
